"""Add batch_id and created_at to send_logs

Revision ID: 767e54592c24
Revises: 001_batch_id_created_at
Create Date: 2026-02-15 23:58:47.258567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '767e54592c24'
down_revision = '001_batch_id_created_at'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
